[project]
name = "parallel_logger"
version = "1.0.0"
description = "Logging utility for parallel processing applications."
readme = "README.md"
authors = [{ name = "Luca Mattiazzi", email = "luca.mattiazzi@illimity.com" }]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
